export const users = [
    {
        id: 1,
        name: "Tony Reichert",
        date_created: "CEO",
        team: "Management",
        status: "active",
        created_by: "29",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
        email: "tony.reichert@example.com",
    },
    {
        id: 2,
        name: "Zoey Lang",
        date_created: "Tech Lead",
        team: "Development",
        status: "paused",
        created_by: "25",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
        email: "zoey.lang@example.com",
    },
    {
        id: 3,
        name: "Jane Fisher",
        date_created: "Sr. Dev",
        team: "Development",
        status: "active",
        created_by: "22",
        avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
        email: "jane.fisher@example.com",
    },
    {
        id: 4,
        name: "William Howard",
        date_created: "C.M.",
        team: "Marketing",
        status: "vacation",
        created_by: "28",
        avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
        email: "william.howard@example.com",
    },
    {
        id: 5,
        name: "Kristen Copper",
        date_created: "S. Manager",
        team: "Sales",
        status: "active",
        created_by: "24",
        avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
        email: "kristen.cooper@example.com",
    },
    {
        id: 6,
        name: "Brian Kim",
        date_created: "P. Manager",
        team: "Management",
        created_by: "29",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
        email: "brian.kim@example.com",
        status: "Active",
    },
    {
        id: 7,
        name: "Michael Hunt",
        date_created: "Designer",
        team: "Design",
        status: "paused",
        created_by: "27",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
        email: "michael.hunt@example.com",
    },
    {
        id: 8,
        name: "Samantha Brooks",
        date_created: "HR Manager",
        team: "HR",
        status: "active",
        created_by: "31",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
        email: "samantha.brooks@example.com",
    },
    {
        id: 9,
        name: "Frank Harrison",
        date_created: "F. Manager",
        team: "Finance",
        status: "vacation",
        created_by: "33",
        avatar: "https://i.pravatar.cc/150?img=4",
        email: "frank.harrison@example.com",
    },
    {
        id: 10,
        name: "Emma Adams",
        date_created: "Ops Manager",
        team: "Operations",
        status: "active",
        created_by: "35",
        avatar: "https://i.pravatar.cc/150?img=5",
        email: "emma.adams@example.com",
    },
    {
        id: 11,
        name: "Brandon Stevens",
        date_created: "Jr. Dev",
        team: "Development",
        status: "active",
        created_by: "22",
        avatar: "https://i.pravatar.cc/150?img=8",
        email: "brandon.stevens@example.com",
    },
    {
        id: 12,
        name: "Megan Richards",
        date_created: "P. Manager",
        team: "Product",
        status: "paused",
        created_by: "28",
        avatar: "https://i.pravatar.cc/150?img=10",
        email: "megan.richards@example.com",
    },
    {
        id: 13,
        name: "Oliver Scott",
        date_created: "S. Manager",
        team: "Security",
        status: "active",
        created_by: "37",
        avatar: "https://i.pravatar.cc/150?img=12",
        email: "oliver.scott@example.com",
    },
    {
        id: 14,
        name: "Grace Allen",
        date_created: "M. Specialist",
        team: "Marketing",
        status: "active",
        created_by: "30",
        avatar: "https://i.pravatar.cc/150?img=16",
        email: "grace.allen@example.com",
    },
    {
        id: 15,
        name: "Noah Carter",
        date_created: "IT Specialist",
        team: "I. Technology",
        status: "paused",
        created_by: "31",
        avatar: "https://i.pravatar.cc/150?img=15",
        email: "noah.carter@example.com",
    },
    {
        id: 16,
        name: "Ava Perez",
        date_created: "Manager",
        team: "Sales",
        status: "active",
        created_by: "29",
        avatar: "https://i.pravatar.cc/150?img=20",
        email: "ava.perez@example.com",
    },
    {
        id: 17,
        name: "Liam Johnson",
        date_created: "Data Analyst",
        team: "Analysis",
        status: "active",
        created_by: "28",
        avatar: "https://i.pravatar.cc/150?img=33",
        email: "liam.johnson@example.com",
    },
    {
        id: 18,
        name: "Sophia Taylor",
        date_created: "QA Analyst",
        team: "Testing",
        status: "active",
        created_by: "27",
        avatar: "https://i.pravatar.cc/150?img=29",
        email: "sophia.taylor@example.com",
    },
    {
        id: 19,
        name: "Lucas Harris",
        date_created: "Administrator",
        team: "Information Technology",
        status: "paused",
        created_by: "32",
        avatar: "https://i.pravatar.cc/150?img=50",
        email: "lucas.harris@example.com",
    },
    {
        id: 20,
        name: "Mia Robinson",
        date_created: "Coordinator",
        team: "Operations",
        status: "active",
        created_by: "26",
        avatar: "https://i.pravatar.cc/150?img=45",
        email: "mia.robinson@example.com",
    },
];
